//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GermanWords.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GermanWords.Resource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 德语词卡 的本地化字符串。
        /// </summary>
        public static string _appName {
            get {
                return ResourceManager.GetString("_appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向左或向右滑动可查看卡片示例 的本地化字符串。
        /// </summary>
        public static string _SeeExamplePrompt {
            get {
                return ResourceManager.GetString("_SeeExamplePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一种词卡开始学习 的本地化字符串。
        /// </summary>
        public static string _SelectModePrompt {
            get {
                return ResourceManager.GetString("_SelectModePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次跳过卡片示例 的本地化字符串。
        /// </summary>
        public static string _SkipCardExamplePrompt {
            get {
                return ResourceManager.GetString("_SkipCardExamplePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有名词 的本地化字符串。
        /// </summary>
        public static string AllNoun {
            get {
                return ResourceManager.GetString("AllNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部单词 的本地化字符串。
        /// </summary>
        public static string AllWords {
            get {
                return ResourceManager.GetString("AllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现顺序 的本地化字符串。
        /// </summary>
        public static string AppearanceOrder {
            get {
                return ResourceManager.GetString("AppearanceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片示例 的本地化字符串。
        /// </summary>
        public static string CardExample {
            get {
                return ResourceManager.GetString("CardExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片类型 的本地化字符串。
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1号卡片 的本地化字符串。
        /// </summary>
        public static string CardTypeNo1 {
            get {
                return ResourceManager.GetString("CardTypeNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2号卡片 的本地化字符串。
        /// </summary>
        public static string CardTypeNo2 {
            get {
                return ResourceManager.GetString("CardTypeNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3号卡片 的本地化字符串。
        /// </summary>
        public static string CardTypeNo3 {
            get {
                return ResourceManager.GetString("CardTypeNo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅阴性名词 的本地化字符串。
        /// </summary>
        public static string Feminine {
            get {
                return ResourceManager.GetString("Feminine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名词词性 的本地化字符串。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正面德语 的本地化字符串。
        /// </summary>
        public static string GermanWordOnFirstSide {
            get {
                return ResourceManager.GetString("GermanWordOnFirstSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背面德语 的本地化字符串。
        /// </summary>
        public static string GermanWordOnSecondSide {
            get {
                return ResourceManager.GetString("GermanWordOnSecondSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string LearningSetting {
            get {
                return ResourceManager.GetString("LearningSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查单词 的本地化字符串。
        /// </summary>
        public static string LookUp {
            get {
                return ResourceManager.GetString("LookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅阳性名词 的本地化字符串。
        /// </summary>
        public static string Masculine {
            get {
                return ResourceManager.GetString("Masculine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中性阳性名词 的本地化字符串。
        /// </summary>
        public static string MasculineOrNeuter {
            get {
                return ResourceManager.GetString("MasculineOrNeuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string MorePage {
            get {
                return ResourceManager.GetString("MorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅中性名词 的本地化字符串。
        /// </summary>
        public static string Nenuter {
            get {
                return ResourceManager.GetString("Nenuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换个单词 的本地化字符串。
        /// </summary>
        public static string NextWord {
            get {
                return ResourceManager.GetString("NextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅名词 的本地化字符串。
        /// </summary>
        public static string NounOnly {
            get {
                return ResourceManager.GetString("NounOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单面词卡 的本地化字符串。
        /// </summary>
        public static string OneSideWordCard {
            get {
                return ResourceManager.GetString("OneSideWordCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅短语 的本地化字符串。
        /// </summary>
        public static string PhraseOnly {
            get {
                return ResourceManager.GetString("PhraseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小测验 的本地化字符串。
        /// </summary>
        public static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机 的本地化字符串。
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除缓存 的本地化字符串。
        /// </summary>
        public static string RemoveFiles {
            get {
                return ResourceManager.GetString("RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序 的本地化字符串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始学习 的本地化字符串。
        /// </summary>
        public static string StartLearning {
            get {
                return ResourceManager.GetString("StartLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日单词 的本地化字符串。
        /// </summary>
        public static string TodayWord {
            get {
                return ResourceManager.GetString("TodayWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具+百宝箱 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双面词卡 的本地化字符串。
        /// </summary>
        public static string TwoSidesWordCard {
            get {
                return ResourceManager.GetString("TwoSidesWordCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅动词 的本地化字符串。
        /// </summary>
        public static string VerbOnly {
            get {
                return ResourceManager.GetString("VerbOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来自： 的本地化字符串。
        /// </summary>
        public static string WordFrom {
            get {
                return ResourceManager.GetString("WordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单词来源 的本地化字符串。
        /// </summary>
        public static string WordSource {
            get {
                return ResourceManager.GetString("WordSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单词类型 的本地化字符串。
        /// </summary>
        public static string WordType {
            get {
                return ResourceManager.GetString("WordType", resourceCulture);
            }
        }
    }
}
